import json
from pathlib import Path

from django.core.management.base import BaseCommand, CommandError
from django.db import transaction

from pronunciation.models import (
    PracticeSentence,
    PronunciationAnalysis,
    PronunciationCategory,
)


class Command(BaseCommand):
    help = "Import validated practice sentence JSON generated by build_sentence_import.py"

    def add_arguments(self, parser):
        parser.add_argument("json_path", type=Path)
        parser.add_argument("--remove-text", action="append", default=[])
        parser.add_argument("--allow-delete-pending-analysis", action="store_true")
        parser.add_argument(
            "--replace-default",
            action="store_true",
            help="Deactivate public default sentences that are not present in the import file.",
        )
        parser.add_argument("--dry-run", action="store_true")

    def handle(self, *args, **options):
        records = json.loads(options["json_path"].read_text(encoding="utf-8"))
        if not isinstance(records, list) or not records:
            raise CommandError("import JSON must be a non-empty list")
        texts = [record.get("text") for record in records]
        if len(texts) != len(set(texts)) or any(not text for text in texts):
            raise CommandError("sentence text must be non-empty and unique")
        valid_difficulties = set(PracticeSentence.Difficulty.values)
        for index, record in enumerate(records, start=1):
            if record.get("difficulty") not in valid_difficulties:
                raise CommandError(f"record {index}: invalid difficulty")
            if not record.get("cached_ipa") or not record.get("word_spans"):
                raise CommandError(f"record {index}: IPA and word spans are required")
            ipa_variants = record.get("cached_ipa_variants") or [
                {"label": "standard", "ipa": record["cached_ipa"]}
            ]
            if not isinstance(ipa_variants, list) or not ipa_variants:
                raise CommandError(f"record {index}: IPA variants must be a non-empty list")
            for variant_index, variant in enumerate(ipa_variants, start=1):
                variant_ipa = variant.get("ipa") if isinstance(variant, dict) else variant
                if not isinstance(variant_ipa, list) or not variant_ipa:
                    raise CommandError(
                        f"record {index}: IPA variant {variant_index} must include ipa"
                    )
            record["cached_ipa_variants"] = ipa_variants
            if not record.get("category", {}).get("code"):
                raise CommandError(f"record {index}: category is required")

        with transaction.atomic():
            removed_analyses = 0
            removed_sentences = 0
            for text in options["remove_text"]:
                sentence_queryset = PracticeSentence.objects.filter(text=text)
                analysis_queryset = PronunciationAnalysis.objects.filter(
                    sentence__in=sentence_queryset
                )
                protected = analysis_queryset.exclude(
                    status=PronunciationAnalysis.Status.PENDING,
                    score__isnull=True,
                )
                if protected.exists():
                    raise CommandError(
                        f"{text!r} has completed or processing analyses and cannot be removed"
                    )
                if analysis_queryset.exists() and not options["allow_delete_pending_analysis"]:
                    raise CommandError(
                        f"{text!r} has pending analyses; pass --allow-delete-pending-analysis"
                    )
                removed_analyses += analysis_queryset.delete()[0]
                removed_sentences += sentence_queryset.delete()[0]

            categories = {}
            for record in records:
                category_data = record["category"]
                category, _ = PronunciationCategory.objects.update_or_create(
                    code=category_data["code"],
                    defaults={
                        "name": category_data["name"],
                        "description": category_data.get("description", ""),
                    },
                )
                categories[category.code] = category

            created = 0
            updated = 0
            for record in records:
                _, was_created = PracticeSentence.objects.update_or_create(
                    text=record["text"],
                    defaults={
                        "cached_ipa": record["cached_ipa"],
                        "cached_ipa_variants": record["cached_ipa_variants"],
                        "word_spans": record["word_spans"],
                        "source_metadata": record.get("source_metadata", {}),
                        "difficulty": record["difficulty"],
                        "category": categories[record["category"]["code"]],
                        "is_active": True,
                    },
                )
                created += int(was_created)
                updated += int(not was_created)

            deactivated = 0
            if options["replace_default"]:
                deactivated = PracticeSentence.objects.filter(
                    created_by__isnull=True,
                    is_active=True,
                ).exclude(text__in=texts).update(is_active=False)

            self.stdout.write(
                self.style.SUCCESS(
                    f"created={created} updated={updated} "
                    f"deactivated={deactivated} "
                    f"removed_sentences={removed_sentences} "
                    f"removed_analysis_rows={removed_analyses}"
                )
            )
            if options["dry_run"]:
                transaction.set_rollback(True)
                self.stdout.write(self.style.WARNING("dry-run: transaction rolled back"))
