# Generated by Django 5.2.16 on 2026-07-16 13:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticeSentence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "text",
                    models.CharField(max_length=255, unique=True, verbose_name="연습 문장"),
                ),
                ("cached_ipa", models.TextField(blank=True, verbose_name="목표 IPA 캐시")),
                (
                    "word_spans",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='예: [{"word": "갑니다", "start": 0, "end": 7}]',
                        verbose_name="단어-음소 위치 매핑",
                    ),
                ),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "초급"), (2, "중급"), (3, "고급")],
                        default=1,
                        verbose_name="난이도",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="사용 여부")),
            ],
            options={
                "verbose_name": "연습 문장",
                "verbose_name_plural": "연습 문장",
                "db_table": "practice_sentence",
                "ordering": ["difficulty", "id"],
            },
        ),
        migrations.CreateModel(
            name="PronunciationCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(unique=True, verbose_name="분류 코드")),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="분류명"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
            ],
            options={
                "verbose_name": "발음 분류",
                "verbose_name_plural": "발음 분류",
                "db_table": "pronunciation_category",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PronunciationAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("target_ipa", models.TextField(verbose_name="목표 IPA")),
                (
                    "recognized_ipa",
                    models.TextField(blank=True, verbose_name="사용자 IPA"),
                ),
                (
                    "alignment",
                    models.JSONField(
                        blank=True, default=list, verbose_name="IPA 정렬 결과"
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="발음 점수",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "분석 대기"),
                            ("completed", "분석 완료"),
                            ("failed", "분석 실패"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="분석 상태",
                    ),
                ),
                (
                    "consent_to_store",
                    models.BooleanField(
                        default=True,
                        help_text="동의하지 않은 분석 결과는 데이터베이스에 생성하지 않습니다.",
                        verbose_name="기록 저장 동의",
                    ),
                ),
                (
                    "processing_ms",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="처리 시간(ms)"
                    ),
                ),
                (
                    "analyzer_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="G2P, Allosaurus, inventory 버전 등 재현에 필요한 정보",
                        verbose_name="분석기 메타데이터",
                    ),
                ),
                ("failure_reason", models.TextField(blank=True, verbose_name="실패 사유")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sentence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analyses",
                        to="pronunciation.practicesentence",
                        verbose_name="연습 문장",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pronunciation_analyses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "발음 분석 기록",
                "verbose_name_plural": "발음 분석 기록",
                "db_table": "pronunciation_analysis",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CorrectionFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.CharField(max_length=500, verbose_name="피드백 요약")),
                ("content", models.TextField(verbose_name="교정 피드백")),
                (
                    "priority_items",
                    models.JSONField(blank=True, default=list, verbose_name="교정 우선순위"),
                ),
                (
                    "structured_output",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="LLM 구조화 출력"
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="LLM 모델명"
                    ),
                ),
                (
                    "model_version",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="LLM 모델 버전"
                    ),
                ),
                (
                    "is_validated",
                    models.BooleanField(default=False, verbose_name="규칙 검증 통과 여부"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "analysis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="pronunciation.pronunciationanalysis",
                        verbose_name="분석 기록",
                    ),
                ),
            ],
            options={
                "verbose_name": "교정 피드백",
                "verbose_name_plural": "교정 피드백",
                "db_table": "correction_feedback",
            },
        ),
        migrations.AddField(
            model_name="practicesentence",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sentences",
                to="pronunciation.pronunciationcategory",
                verbose_name="발음 분류",
            ),
        ),
        migrations.CreateModel(
            name="PronunciationError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField(verbose_name="오류 순서")),
                (
                    "phone_position",
                    models.PositiveIntegerField(verbose_name="목표 IPA 위치"),
                ),
                (
                    "word",
                    models.CharField(blank=True, max_length=100, verbose_name="오류 단어"),
                ),
                (
                    "word_index",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="문장 내 단어 위치"
                    ),
                ),
                (
                    "target_phone",
                    models.CharField(blank=True, max_length=20, verbose_name="목표 음소"),
                ),
                (
                    "recognized_phone",
                    models.CharField(blank=True, max_length=20, verbose_name="인식 음소"),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("substitution", "대체"),
                            ("deletion", "삭제"),
                            ("insertion", "삽입"),
                            ("weakening", "약화"),
                        ],
                        max_length=20,
                        verbose_name="오류 유형",
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="인식 신뢰도",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errors",
                        to="pronunciation.pronunciationanalysis",
                        verbose_name="분석 기록",
                    ),
                ),
            ],
            options={
                "verbose_name": "발음 오류",
                "verbose_name_plural": "발음 오류",
                "db_table": "pronunciation_error",
                "ordering": ["sequence"],
            },
        ),
        migrations.AddIndex(
            model_name="pronunciationanalysis",
            index=models.Index(
                fields=["user", "-created_at"], name="analysis_user_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pronunciationanalysis",
            index=models.Index(
                fields=["sentence", "-created_at"], name="analysis_sentence_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pronunciationanalysis",
            index=models.Index(
                fields=["status", "-created_at"], name="analysis_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="pronunciationanalysis",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("score__isnull", True),
                    models.Q(("score__gte", 0), ("score__lte", 100)),
                    _connector="OR",
                ),
                name="analysis_score_0_to_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="pronunciationanalysis",
            constraint=models.CheckConstraint(
                condition=models.Q(("consent_to_store", True)),
                name="analysis_requires_consent",
            ),
        ),
        migrations.AddIndex(
            model_name="practicesentence",
            index=models.Index(
                fields=["is_active", "difficulty"], name="sentence_active_diff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="practicesentence",
            index=models.Index(
                fields=["category", "is_active"], name="sentence_category_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="practicesentence",
            constraint=models.CheckConstraint(
                condition=models.Q(("difficulty__in", [1, 2, 3])),
                name="sentence_valid_difficulty",
            ),
        ),
        migrations.AddIndex(
            model_name="pronunciationerror",
            index=models.Index(
                fields=["analysis", "operation"], name="error_analysis_op_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pronunciationerror",
            index=models.Index(
                fields=["target_phone", "recognized_phone"], name="error_phone_pair_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="pronunciationerror",
            constraint=models.UniqueConstraint(
                fields=("analysis", "sequence"), name="error_unique_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="pronunciationerror",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("confidence__isnull", True),
                    models.Q(("confidence__gte", 0), ("confidence__lte", 1)),
                    _connector="OR",
                ),
                name="error_confidence_0_to_1",
            ),
        ),
    ]
