# Generated by Django 5.2.16 on 2026-07-24 07:19

import json

import django.core.validators
from django.db import migrations, models


def convert_ipa_text_to_json(apps, schema_editor):
    practice_sentence = apps.get_model("pronunciation", "PracticeSentence")
    pronunciation_analysis = apps.get_model("pronunciation", "PronunciationAnalysis")

    for sentence in practice_sentence.objects.only("id", "cached_ipa").iterator():
        sentence.cached_ipa = _as_json_array(sentence.cached_ipa)
        sentence.save(update_fields=["cached_ipa"])

    for analysis in pronunciation_analysis.objects.only(
        "id", "target_ipa", "recognized_ipa"
    ).iterator():
        analysis.target_ipa = _as_json_array(analysis.target_ipa)
        analysis.recognized_ipa = _as_json_array(analysis.recognized_ipa)
        analysis.save(update_fields=["target_ipa", "recognized_ipa"])


def convert_ipa_json_to_text(apps, schema_editor):
    practice_sentence = apps.get_model("pronunciation", "PracticeSentence")
    pronunciation_analysis = apps.get_model("pronunciation", "PronunciationAnalysis")

    for sentence in practice_sentence.objects.only("id", "cached_ipa").iterator():
        sentence.cached_ipa = _as_text(sentence.cached_ipa)
        sentence.save(update_fields=["cached_ipa"])

    for analysis in pronunciation_analysis.objects.only(
        "id", "target_ipa", "recognized_ipa"
    ).iterator():
        analysis.target_ipa = _as_text(analysis.target_ipa)
        analysis.recognized_ipa = _as_text(analysis.recognized_ipa)
        analysis.save(update_fields=["target_ipa", "recognized_ipa"])


def _as_json_array(value):
    if not value:
        return "[]"

    try:
        parsed = json.loads(value)
    except (TypeError, json.JSONDecodeError):
        parsed = str(value).split()

    if not isinstance(parsed, list):
        parsed = [str(parsed)]
    return json.dumps(parsed, ensure_ascii=False)


def _as_text(value):
    if not value:
        return ""

    try:
        parsed = json.loads(value) if isinstance(value, str) else value
    except json.JSONDecodeError:
        return str(value)

    if isinstance(parsed, list):
        return " ".join(str(item) for item in parsed)
    return str(parsed)


class Migration(migrations.Migration):
    dependencies = [
        ("pronunciation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="pronunciationanalysis",
            name="analysis_requires_consent",
        ),
        migrations.AddField(
            model_name="pronunciationanalysis",
            name="expires_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="임시 결과 만료 시각"
            ),
        ),
        migrations.RunPython(
            convert_ipa_text_to_json,
            reverse_code=convert_ipa_json_to_text,
        ),
        migrations.AlterField(
            model_name="practicesentence",
            name="cached_ipa",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='예: ["h", "a", "k̚", "k͈", "j", "o"]',
                verbose_name="목표 IPA 캐시",
            ),
        ),
        migrations.AlterField(
            model_name="pronunciationanalysis",
            name="consent_to_store",
            field=models.BooleanField(
                default=False,
                help_text="미동의 분석 결과는 완료 후 30분 동안만 임시 보관합니다.",
                verbose_name="기록 저장 동의",
            ),
        ),
        migrations.AlterField(
            model_name="pronunciationanalysis",
            name="recognized_ipa",
            field=models.JSONField(blank=True, default=list, verbose_name="사용자 IPA"),
        ),
        migrations.AlterField(
            model_name="pronunciationanalysis",
            name="score",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=4,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="발음 점수",
            ),
        ),
        migrations.AlterField(
            model_name="pronunciationanalysis",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "분석 대기"),
                    ("processing", "분석 중"),
                    ("completed", "분석 완료"),
                    ("failed", "분석 실패"),
                ],
                default="pending",
                max_length=20,
                verbose_name="분석 상태",
            ),
        ),
        migrations.AlterField(
            model_name="pronunciationanalysis",
            name="target_ipa",
            field=models.JSONField(default=list, verbose_name="목표 IPA"),
        ),
    ]
