# Generated by Django 5.2.16 on 2026-07-24 07:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "pronunciation",
            "0002_remove_pronunciationanalysis_analysis_requires_consent_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="pronunciationanalysis",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["pending", "processing", "completed", "failed"])
                ),
                name="analysis_valid_status",
            ),
        ),
    ]
