# Generated by Django 5.2.16 on 2026-08-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pronunciation", "0003_pronunciationanalysis_analysis_valid_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="pronunciationanalysis",
            name="request_fingerprint",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="사용자 ID, 문장 ID와 음성 바이트로 계산한 SHA-256 값",
                max_length=64,
                verbose_name="중복 요청 식별값",
            ),
        ),
        migrations.AddField(
            model_name="pronunciationerror",
            name="specific_feedback",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Qwen이 생성한 summary, content, practice_tip 구조",
                verbose_name="오류별 교정 피드백",
            ),
        ),
    ]
