# Generated by Django 5.2.17 on 2026-08-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronunciation', '0004_pronunciationanalysis_request_fingerprint_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='practicesentence',
            name='sentence_valid_difficulty',
        ),
        migrations.AddField(
            model_name='practicesentence',
            name='source_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='원본 행, g2pK 표준 발음, 변환기 버전 등 재현 정보', verbose_name='문장 생성 메타데이터'),
        ),
        migrations.AlterField(
            model_name='practicesentence',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(1, '초급'), (2, '중급'), (3, '고급'), (4, '특수')], default=1, verbose_name='난이도'),
        ),
        migrations.AddConstraint(
            model_name='practicesentence',
            constraint=models.CheckConstraint(condition=models.Q(('difficulty__in', [1, 2, 3, 4])), name='sentence_valid_difficulty'),
        ),
    ]
