# Generated by Django 5.2.17 on 2026-09-01 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronunciation', '0005_remove_practicesentence_sentence_valid_difficulty_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesentence',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='비어 있으면 모든 사용자에게 보이는 기본 문장입니다.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_practice_sentences', to=settings.AUTH_USER_MODEL, verbose_name='문장 생성 사용자'),
        ),
        migrations.AlterField(
            model_name='practicesentence',
            name='text',
            field=models.CharField(max_length=255, verbose_name='연습 문장'),
        ),
        migrations.AddIndex(
            model_name='practicesentence',
            index=models.Index(fields=['created_by', 'is_active'], name='sentence_owner_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='practicesentence',
            constraint=models.UniqueConstraint(fields=('created_by', 'text'), name='sentence_unique_owner_text'),
        ),
    ]
