# Generated by Django 5.2.17 on 2026-08-26 13:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='연령'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='아이디'),
        ),
        migrations.CreateModel(
            name='SpeechBaselineAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('completed', '완료'), ('skipped', '건너뜀')], max_length=20, verbose_name='상태')),
                ('answers', models.JSONField(blank=True, default=dict, verbose_name='자가 보고 응답')),
                ('self_report_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='자가 보고 불편 점수')),
                ('discomfort_level', models.CharField(blank=True, choices=[('low', '낮음'), ('medium', '보통'), ('high', '높음')], default='', max_length=10, verbose_name='자가 보고 불편 수준')),
                ('assessment_version', models.CharField(default='self-report-v1', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='speech_baseline_assessment', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '초기 발음 상태 평가',
                'verbose_name_plural': '초기 발음 상태 평가',
                'db_table': 'speech_baseline_assessment',
                'ordering': ['-updated_at'],
            },
        ),
    ]
